apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otterwiki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    chart: otterwiki
    repoURL: https://charts.otterwiki.com
    targetRevision: 0.1.0
    helm:
      releaseName: otterwiki
      values: |
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            cert-manager.io/cluster-issuer: "home-issuer"  
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          hosts:
            - host: otterwiki.rafa.local
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - otterwiki.rafa.local
              secretName: otterwiki-tls   

          resources: 
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

          persistence:
            enabled: true
            storageClass: longhorn
            size: 512Mi
            accessMode: ReadWriteOnce
  destination:
    server: https://kubernetes.default.svc
    namespace: otterwiki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true