---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook-secret
  namespace: alerts
spec:
  encryptedData:
    url: AgA8pi6igdpRl8s9yjxp+FI9eMmgPVVnvCSFKUU6F+mkwF7DBFVOaXtlPAxlNNNnv/jYEA6SFRGTNvrBySOSEkNbk6L6YShOGimOFJLs+FfyDcAE8ir4QHP9KoyL/9OTOouJOyTOY9LLsGbNEGKlVFW09I/GVOM34IfYZChe5dsLO70HKuwkhbM/E286LZJSur/c0XY+bFop197OEQdzTghyPXWYNfdo2o1aVrd5zTz7oVPGoSWkCoP57QkTHGx/yzgwPU03rTEf1CsRtxhUxGMJ4U1CK6dKIY3wG41YhxP/xXNX8Y0SV1SU2XGaOJ5jTOZIyU2Hp9ZA4hCcV/mfLCS/U5kVPc9wdLjnwqUWkaG2mqweS4p1e2adxd+2xvte3QHJXalbZJ9bW5XXtADqaI8QLJiDosCTz95UIQrmWhAEA5xQY9wPxkOhCWrBaiHpcgjyd/ZFR333s7CnFiWbsKjsbUFHX3Po7ZNK1I9PMWoGBNv1NQpY95sqHTwSKKzb/fvMvqbFB2vbBlhQ4hQ2n8+WB47vVBNIRvLNjdaG6VmAd98ZTJpQynTCwFxekQPM8Oa3ZviUDVlQautfK8ekb7C1/wEFvyeSq4wqP1ZbXtnjHgI66YYIFmI3YIq5FF1v8rSlVVQ1/GsHhLyeg381HrKTfMuQaDIKWwLLXlzqDlWEHg+J1Umbb66AnBU3agldAKkLhwJauNilvSGf333hNV5SrkhJJ+ftOZc62Vt22yyYSDC4j3VUGenLj7ztKuVjeEsgDmPsMrlGf3jFTevhXylNz2m+1ugfnAY31NihSXshYKB39E2yz+TuOa6nTB0QlQnUUOuxMOTaLT+EsvZtWicCUM6oiTaXOQuM
  template:
    metadata:
      name: discord-webhook-secret
      namespace: alerts
    type: Opaque
