pms:
  configExistingClaim: "plex-config-pvc"
  claimSecret:
    name: "plex-claim-secret"
    key: "plex-claim"
    value: "default"
  resources:
    requests:
      cpu: 500m  
      memory: 1Gi 
    limits:
      cpu: 1000m     
      memory: 2Gi     
  livenessProbe:
    httpGet:
      path: /identity
      port: 32400
    initialDelaySeconds: 60
    periodSeconds: 60
    timeoutSeconds: 1
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /identity
      port: 32400
    initialDelaySeconds: 60
    periodSeconds: 60
    timeoutSeconds: 1
    failureThreshold: 3
service:
  type: LoadBalancer
  port: 32400
extraVolumes:
- name: nfs-data
  persistentVolumeClaim:
    claimName: plex-data-pvc
extraVolumeMounts:
- mountPath: /data
  name: nfs-data