apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    chart: immich
    repoURL: https://immich-app.github.io/immich-charts
    targetRevision: 0.9.3
    helm:
      releaseName: immich
      values: |
        env:
          REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
          DB_HOSTNAME: "db-cluster-rw.svc.cluster.local"
          IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'

        immich:
          metrics:
            enabled: true
          persistence:
            library:
              existingClaim: immich-library-pvc
        postgresql:
          global:
            postgresql:
              auth:
                existingSecret: immich-db-secret
        redis:
          enabled: true
          architecture: standalone
          auth:
            enabled: false
          master:
            persistence:
              enabled: true
              size: 2Gi
              storageClass: longhorn
        server:
          enabled: true
          image:
            repository: ghcr.io/immich-app/immich-server
            pullPolicy: IfNotPresent
          ingress:
            main:
              enabled: true
              annotations:
                # proxy-body-size is set to 0 to remove the body limit on file uploads
                nginx.ingress.kubernetes.io/proxy-body-size: "0"
                kubernetes.io/ingress.class: "nginx"
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                cert-manager.io/cluster-issuer: "home-issuer"  
                nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
              hosts:
                - host: immich.rafa.local
                  paths:
                    - path: "/"
              tls:
                - hosts:
                    - immich.rafa.local
                  secretName: immich-tls   
        machine-learning:
          enabled: true
          image:
            repository: ghcr.io/immich-app/immich-machine-learning
            pullPolicy: IfNotPresent
          env:
            TRANSFORMERS_CACHE: /cache
          persistence:
            cache:
              enabled: true
              size: 3Gi
              type: emptyDir
              accessMode: ReadWriteMany
              # storageClass: longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: git@github.com:racela/home-server-argocd.git
    path: apps/config/immich
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true