---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backup-reporting
  namespace: gatus
spec:
  encryptedData:
    GATUS_ETCD_BACKUP_TOKEN: AgCeRTHyrSgfq+q9IONPdn1iMroh/992rl/n8PyYx7miE8U3sQAxOExUS4aOmnCib5Q+gv/F4FIel30cxcYPoJk0f5Zs0rdK2nrwd2umABm74USsOFRaHZOE83fsnSDw6Y1u+vP8Pm8CkjoI76elP+GNqhrW9alebaIyL8reGBVjscvZXxaG9kzsKB3BUyq8jE6Vvpe4VIRbg73LEVzozLfpsZFAK7bodW9Jake1Pn28fy0IGJhOTXu25k42QOBqRlVUSe8eJTNM1rmID3fEBUdLdA2KxXlXCu1FmSTEL7vXBWbeR3Wjp4cq1BUfpCHTzGFGExyrVXDg9gekjlqulAjRUueKSPLajPIgDrnsKWxfM/i19sTwVL/98PfP5R2ljBYGLvDQoam1RKCO3Jii8HzCBd3GaoH24D1jhXHcwY04ASaQi8sSIOR0LPX9kbagnMzj1gIlJf0pWkd9hV2S5aPQSI9fe+C/d4fix4SCJciADSfidVwuw6d9btEBNJ9kb6Grs8/+1PYR01FnI97sFCdgTEYybJbpe47SNtOyDuy5NnQa+sEAbe8SOivhOn0JeFN1lsEEI+zuSC6FCHb2HbnPfNsT+zSIbmOqMaJ/JUb/8bZ7bfzSG1dWGMaQezTRj5MB8WMPvgd+t8tkbwb2ZZbkgGmFklIXX0yIsx2RNm5h9+3xsewD0SScfhX5CPbLPrx6yOib812oLCk6NjjAzSS++g229wNdE23WEVKiEUuRYa3wGlsyQOvNMsot
    GATUS_IMMICH_BACKUP_TOKEN: AgAhQeelsqQ5yRAyiybKP57RQYc3RRZeD2tOUKsf4ceFYeKqfG5oul1FIGgK2+rfFqFvPTRmnJ/L/3YAiFb3tGJ1BGJ6cYMRg9z1WpWqRSfC91kI9lJ7vpVb/HQK94XCNMRtvuaa+0zkm82KI/QllrwWJYRFQm4NmR8KIQ1k10+ye/HC1OPNB75pkDWGBMYDfb43Wal1gBGls0aKVMc5AJOnqW+CXjKG4gJj1ZJ/6skGg03Mn5LrQl9Hq76jdFKKClbnoBkGWamETbY4QV50BjwdUtkcj08bBhqZu3kefx1mIPYzM8bZ4KpD0Fd3YLw7yZpJybONVQ+KoyZ+2hyyEw6WcDVFIaMt9754tQMgULtF7sEZrMsrA4cYAeEyK4ZQTixkCX0oZLYIxJC11SroBzd7ads2ZT9fEoYoDjnG9t36zV83JekGZPfS/Fxg+B2sD/HVf8825F2DH/g6Cd6IkS/USvkMsoU0qB+HjyITkqrIbAzCtH3VbwGV6u+Xs7OyVdFPEXcd6QMKV5bcAc2zqPEn+NFJA3aJudFHa/a2TV15cIro0hoQQcKqWXojOOnhSv342bVlLanO+N++uFqruaZpMP0G7cXAZlOc0l4CmG3Cb9ifxy+mTUrpePltrlW2oTbLnQqmCWhqGde5y+guwuF4A5nNKf86QMTXcv12UF1XWE/QdVl+1h9GdtHX0fVRStv15IVEj+reaf65sVSasGtLCHgzMb1rtnP1Le73WXFrUQ4jVfeDlqKhjQCh
  template:
    metadata:
      name: backup-reporting
      namespace: gatus
    type: Opaque
