---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gatus-cronjob-secret
  namespace: gatus
spec:
  encryptedData:
    TARGET_URL: AgBpqTpKUWU7pLSLUswsiArD4t73xi1fzPpXsO/77m/L5E3rJHYq5gUinISv8NtOBjBfQPaXVnfgBPOGYbKGjEQwOZWuntdKJuqXXuPxRP4BP1+SBk2A+cwRHoXza/46hnqjtkPGZvOrVE4zeXFXSq3Dbp6ASYVDN4TY9PAL+d2XHdP8Po2pZo3h5fBFey8mtCVrSXGcvm2VV+4drWQKu4LGvYLuGRJSPN6jFrn/W81twx0iak9RmqBc0+/n1Bx+SFiE4uJWtXwVAwTABfD773t6ivDkzaJwrNiluv8x1JPuYoFmQ87/cuQPREmUCb8w7uYZ5teN25GwGXdDrUdnpjVKkZdd9GmrGxySjYzQQBTCEfkjnQNaievRpOWprFRgF4Eo/ldkmhFiPf6fbDki2rCLmxZELEYAFOENoQ0CinLF3DarYJbgXOqEKqoET0r96eVD6jmH5UyXPkrneL1zfs4GKHjjU6lTFKcIEYlu5/pv9HFU6pwiLh2yZ8wQ6JTst1BCWvRWexy1AWL/gPLlMspuXqmI7j2thvTEVrIhUOZh7e+BGbRPxJBxCShrPsGeZmi+xaB/36mcm6NcKf0S7KIlCumB1gaU2XcnsCodNerb4XIm8kvt+cwOXrUtvXR+E0h3/8GuC7Ydz13Rv9jFOaRq74ppqOEUTpADq2TCyDxLmx9TzvJkfFCYtGMRqtKRodz98MXOHzykRtlX50+I99kWvQQovB7872UH7YoagjkHKQwJGSNK6zOQwmMZkZbRvKExY0flQp0ZVQ==
  template:
    metadata:
      name: gatus-cronjob-secret
      namespace: gatus
    type: Opaque
