---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-alerts
  namespace: gatus
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgC4WmY1+CWAU3f72NPj6Kdkvi+AKgIGS6vZZjPzzwFrBzmEzK1nHqbZRK0l4QnS0gbU9muy9OJRFdZkFgXAqUAZr5KA4W19IB0xxsjVolkVRCDzXf0ZFNyyTPUk1e3KAgCwzLhuR6ZNNMPAruyWAlNSE0B40NXVtgeZ7pMPsBDjop90IukqW0kNOkxLltMRrVRkNDQBmhnOn1H6cNIM8RbLiSBS1mUalqHBQX6CxbQB0fHQPGi+XVvTHVt4j4ItxC2UMAYlY0uNKiGKH+ofrkvgR1fAoRleBtCegzQfyRZxUsI1d2Su1nAmDGvclqDqD1KkprQeRy189oalN0pIwJLrZnSjFMcG7bj9ZehmDw5Jp0NxLhqPSxjjFB3LtM7C60fQVFf4ZkjnQeoV6I23uf3CuS3OwCkpOY7VrYx8dX6LqoQtzGhopVmQ1+J2rtN/eub1a+iqtU+BIcNLtnhmqTZ6Vfp3j4l7wcKdQF5lM67Jhn9RPi9SQloPBOyxjUqKAimJXI2WNXMBXNlmnsgoxUKIo6JQKCGvADnYE7JjQe4cmx48arW19ti/ApA82dQ3XJKV/p5ecXCCoJrxGd4WhJRApu3dJl13xDLE/IuxXcOXSPDPMlTnnvcBHb8o/sEmnRTnvvt4+l1/0tbO+J+CfVBtQzPzl4bOFJS8p2+hTwq0XhiVmyrwrkyMMydyrDqxQSw4SFspUrT0W+syjv6wDQo5z2QTt2n/h9kgUbDJ/7eaaxEFfMt/mb1NQBNA2QuG
    TELEGRAM_CHAT_ID: AgDFrYEgnUvOMTuFrBvEH3MIrO1QDi65xE4FLPrYwNscVWtNDoI1pMtNbbv92E5w/WJxUugvpFQRsqC2QbK0KBKkoVGXzUJrvojYYtSV6w5wv2MjcXN7YP3kEiluOBEaTSjbBB4lVO4wQaiTjJR6M+GSHQLuc/BVPDZgWsO0ZzzaMLyyg+4hL38KoXkJaiTz4aU7UIHOcyhk4TlX9ajE22ByP0JDHShm0alVd5g1mDIJkGRiNTt7EWPuwP6y3P+Q2a/7/WgPcEa3MRdJkpbzk4vzdM5mbChvZVy2AA9ODXqwW77gA6aytU2WBMHmpLCAySzY8GNrArProml/vc7FYKQxIOevL15bOkiZ1eU/RUoQxnlb5pA8dW9xPv/lfCWkjuNMZ+rrcnGe1A9xcyheSWEM1o4bTExvDkuvXe+sbwNH8RMP9jE3pxnUITmWrTJ8HaEzMUGZL1CnB1e6lyc/AtExlMzBmvoIuOQq9LVpNsMZwUhme6TaJBFMuCM68D39xwsNHmWQRNCYPfw5YWG0/V9hZg6MyyDlK5SLyC4VI1lZZXFi8RC6wwV7o4rntDYKS7JpnNCyPKjR80L+GX5GTbsPB3LkHIUC3Y3mKzbd7gZimqqXXQqMeIsAGC4vck+HJNDnNzjW6yXAT+Qwn0/crcDt9iOjDfPR8eDec9lWlx9cXRdZ6Ko5Ct28eZgE9RdksfxYRuQxPzTdtXlF
  template:
    metadata:
      name: telegram-alerts
      namespace: gatus
    type: Opaque
