apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    chart: plex-media-server
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    targetRevision: 1.1.2
    helm:
      releaseName: plex
      values: |
        pms:
          configExistingClaim: plex-config-pvc
          claimSecret:
            name: plex-claim-secret
            key: plex-claim
            value: default
          resources:
            requests:
              cpu: 500m  
              memory: 1Gi 
            limits:
              cpu: 1000m     
              memory: 2Gi     
          livenessProbe:
            httpGet:
              path: /identity
              port: 32400
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /identity
              port: 32400
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 1
            failureThreshold: 3
        service:
          type: LoadBalancer
          port: 32400
          externalTrafficPolicy: Local
        extraVolumes:
        - name: nfs-movies
          persistentVolumeClaim:
            claimName: plex-movies-pvc
        - name: nfs-series
          persistentVolumeClaim:
            claimName: plex-series-pvc
        extraVolumeMounts:
        - mountPath: /movies
          name: nfs-movies 
          readOnly: true
        - mountPath: /series
          name: nfs-series 
          readOnly: true
  destination:
    server: https://kubernetes.default.svc
    namespace: plex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: git@github.com:racela/home-server-argocd.git
    path: apps/config/plex
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: plex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true