crds:
  enabled: true
replicaCount: 1
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingressShim:
  defaultIssuer:
    name: letsencrypt-staging
    kind: ClusterIssuer
# Use HTTP-01 solver with local ingress
  http01:
    ingressClass: nginx