apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-configmap
  namespace: blocky
data:
  config.yml: |
    upstreams:
      groups:
        default:
          - 1.1.1.1
          - 8.8.8.8
    blocking:
      denyLists:
        ads:
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.txt
      clientGroupsBlock:
        default:
          - ads
    ports:
      dns: 53
      http: 4000
    customDNS:
      customTTL: 1h
      mapping:
        # ingress-nginx LoadBalancer IP
        rafa.local: 192.168.1.240