apiVersion: v1
kind: Service
metadata:
  name: blocky-udp-lb
  namespace: blocky
  annotations:
        metallb.universe.tf/allow-shared-ip: 'blocky'
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.242
  selector:
    app: blocky
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: blocky-tcp-lb
  namespace: blocky
  annotations:
        metallb.universe.tf/allow-shared-ip: 'blocky'
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.242
  selector:
    app: blocky
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: blocky-http
  namespace: blocky
spec:
  type: ClusterIP
  selector:
    app: blocky
  ports:
    - name: metrics
      port: 4000
      protocol: TCP
      targetPort: 4000