apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.2
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          replicaCount: 1
          nodeSelector: {}
          service:
            type: LoadBalancer        # will get IP from MetalLB
            externalTrafficPolicy: Local
          admissionWebhooks:
            enabled: false
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: git@github.com:racela/home-server-argocd.git
    path: setup/config/ingress-nginx
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default # yamls will provide their own namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true