---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backup-telegram
  namespace: etcd-backup
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgDUrjPU512yvqpbH6101j3mAujKZ4NxpYm+f3R731LkmEyjWmshe46lnkCTp8RRMpV+4uDU3CTbBZKfcOFFYXmU4U/UD5Ibubmkth5Z4gqMCL7f/VPR14IerE49a9c3TTvhhw95L2YvuUROM5mXfi8Sj0d5Kw4YVm4Wsxr8KgABj9Wd7C10vA6+VMtY38eQ6gdN8vtGkf2AGSfLPt4Jd9c6/TRWqrw2dVW4fCUFeGWDXyh7ujylcmAYTe9AMcahLoV+qVnr4JLDALzj8VUKF5Fdr2S4yUoNGxYggl/p0CAsH+wlAlkXXCZTxVoUsZ12JcU9jzxRWVDSraMAe4UlJrvRKDG1y7lQgCcq4lt/jYW2pK2BTxZLxCASMC550LN82izeGPA8wHJPuIK32detnrEPg/oJ33IopIvd4ovw5KjIhIPPD+H5jUY8JOyWFcRtTp9rWBHc7QJIdpe6FACWe7a2myMgPCYR2qTX99u/uJQJ6thokc/MmB/fgmpPl1FuGZ13qwe3daMRL7AI71D+wlFzHO3ZpFXt0J0Orjpe3cs35U+Cfh73GRal9jx8pvvY6YnwWZJ3uOe7D/oiX/qbLj9aaK3rl+Z7XPRcqBM1OmPnkMgiXKGeoWKlOUbmMuo5CzHoPfUu2DUSRBzrBqHdBkim7aMOKgisZRc0tYkxi0ywA2sKxR/WgoFZatrArR1maUMLmXtNrx05cqvvjejVYaqfDiIpYeCuV501YOIxu4VL2LFK+1WSh5X4c3mktpk7
    TELEGRAM_CHAT_ID: AgBRHUQpRsY8L7cnsUXJlWQUBpA0BUxS3vxoyVUJQA3fscJof4UNgfVD5i5vZim7uB/TB+l2dVjKrfLsaWed2EkKnZlufPWJzK1je9mFKpjc++1y6EB21FoRM3mmFYb5RtV7ukNlbuwtK3HWa45UvFCwtLYyO+1g/n9XVjhYdoHu8EW6bHPnysZyCrJx/g7oWPzq/WPh9V0yze5CZjTVThHRM0qReJDzCAte63+IahzablbfpI40GCAxyI028WeLNKIy7JcCZGlY0Uaaf1V6bCAyXUj9Tu4jG+7la7i1lQ67zWMIK0g3Ch/Rjj0t3i6frmQcPr3N0hgoe3i3of7tFk/YvZ3Nk8WA4N0+FzHl35zMlay/JR+rdElzOCgUUYQl70QYaTa4djSBIEFW6DmV38hbVWSJVSL1H31CU+mKdj+MmEeDhE5WI7AZsZxZxicbIM5RHKH76GnMWZ/3NrdstbnWgQb2Qgi+bix46Zj4NxaODQUfpWY4N/03hzrJ15ZCMv1wCQMIVN+TSlOcPBclRGAai01+IGVc7FVvs+RjR2Q455ZtM64XBbhr8R8zaxGgcHCQA24qFMoFRbAmOvBpFnZv1GROr0FZ3HQgbu37VxMddLZ2z8tZN+B0+PQz3pEVi+2hxrvH0bHS2FJtnMqu/2QPfq+Df2lQTazEqCwwtJFQEgcutzhnQ5ZR52uxw01SXW41RUfYjKtyz5Ra
  template:
    metadata:
      name: backup-telegram
      namespace: etcd-backup
    type: Opaque
