---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gatus-backup-reporting
  namespace: etcd-backup
spec:
  encryptedData:
    token: AgDBjgt5j6qXxo2ENbmLMTs9T7DM1tsVSDXtXQ3eVww1kFe650D009fjtqDYS9nyZ0EB2c2HkmdNOyg7RsxNf8Phbywb1PofcJr50d0Z3vRmNAW28oAy/LN69nqyTMKrKQkUhoL8jJaJJruWue1uVkmuogR0Cmmmxzyb2yWNgvP7C7YHw/7dUZgPa+gZ7jZtCtg2JxKIkUg8tiLeMe8p8k7EF2bNredr0gfO5jNcUJEQDheRnWhmYa+MLzYHEwKXIJnJA6OPEaM6XINCYayi+jhJR2tUUfPOp55IG4pjGW70fWtbOfED/jrWr3SHAybBf5V3pVDpe9bNfAiGAZyS2JmxVmDlWFA0q5o8pXTHzDMe1IG87/W35qXOtJrBY5kcx67JCeZNQLoo87/z5kIyLUPyXedz2Sr+ZKDTQxIcvgJmylD3XB4wmi5aElNWNtOyjUcExcmW87z0ZMIv8xjTkjMxR8uXjBXUUERXqcYvV48H0nNcS1yS9Sq+CER92BFuvMsG/3CbzP56K58uh9cdyv6xYOYjbOhWFpW+TkMw/2/+K1pcJIgVcdLSjodXtX5SNDBbu+zpXM3npjq3MSZ+ZudKG0htneaQkdRL7T/zEE8iLcqh9yKCDkxWheLjAtTXp8rliPzzUGZJR0I/Eba+e0Cl+9dQoYCe5YuoPsRUexHhLH6O4TCquQUJXyLWkMny2QSY0RO3eT3yJrlw5AZ6erkpFiV5Wyp018WreOa3i4z3CHcdnSQ7BFwpCp/4
  template:
    metadata:
      name: gatus-backup-reporting
      namespace: etcd-backup
    type: Opaque
