---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAq1rLtd0SKSwBp0k8eVNyBeq22i1606lVo0f8qragsq6Oy+Z70kxHOo9tHv+INKdmJOB8SDOMtPVYpMMJlm0Ft/V24Oqb8jMAGIaQpBMF2rpOR0EVpaxipkCxm0pXgSAcEhM0PcD4MqPSEaDPjfwc/ReJTGQpb8ZhN66LW95uOZOWUc2JGprB2Ltz556tjnDzsYM1cic6fl3gOa3/wQrqKFhupL8ql0JNjYJITLsMjvFkDTtMu54Grkq4y0l8Cp0nFb1B+EAzyOZDAXeBpr9zRc+Oz+CsvAbtYrIJkeSxLGAQkzRkgxpoIVKpQKiv8hYluamn763M5xJoTZJy0l2AuaR3a4HK4P7jY6p1etVjoT+OE83f3oOgzaJ+3jZtfgy8GygK8NpPrxwBKuoRLgYtLZBg1NDjSedIMrsEeaY6tcBTK2G2Fz9YH8xUZx8XRPRVhgMfizI/RguraGjN/I4ni1+lokFkiMlmJs43eat80IHOlbq9/ZyLa2jA3Vy7AQJKOLveSHMEf8uby5sORFoxYv4lHaTfoqj1mQih26W4JePIruaJy+LsFUphEchU4rmvWW4zdYr/qzCtFg1YXEWfcnr/bDsZThr9nnowcrhL0Bx7RgHOdM+o3tVBZ8vIjfKKxqC+Kg/lRAT0Jjh6Zju1/nFmXCi18hLiXhOwLD6SPfDr+BiEpXu6F/K64Yt3WDq67zdaul8Z9b5Vu76qDFD3ToQ==
    client_secret: AgCc8WimKv6KI+n5DpHHg7eIIO9yE1hNJ8xG5fwtqVyPgzfAxbaCGoiml1XjtP+4Y4offtG3ZOxpU1FCOOGRW+k2sS8M7MIEKD3C4AFEUbkF8pUF8CZAF8XYzapbdqM9Mnohq/APyN9W9547X3J+wofUTKoXu3xwV6BxLP7LAIlPqYCWIZFKb7Si3NEBDpbVZtVjCiSUt5b8ACjFZAmtcv3oiVz3WAXhqflaJ8OuvHaBuWGtZi0YAMWh5X1DR/EAXc5XDgA4RErKKJchDqwXSeJMhqYWy2gFthm/w4ofv/R+1u6yK6xFJp2kE5sYWCutvnmwK7bpfgAIWpSPaGB9Ng4C3a15HFYxz/QM7FMcUFD45eBAJNVk+Evw8X1ADm9aEK5HTc49ImlX0MUHVnBM/bDE/to/Vfmgj+MTcJN3QpXRycb+CGpRPl7nTvXkzEdEacey1qB5SD5XJGhEyGCJrut3vAtMXzWpMgbgoGHr+YE5bD092sFL85hw21rjha8lLBwdIqDRig8gn2TsO7hMnbJx4q/rfBOUY4mdOrMfgtgTqtXXlT1DPOZfmiRDA6p7i0fkZCNPuFOZlHgVsq8sLMbmdBuNMTyQcnpPBVD9chIsKEPb9XhHj+LcFlu75KUh/DQWfXuI1ZsXsXRGBbUrhchgcZ0A050uA8lp4Q8Q4/IZZ3cv2u3VsXOkdSZYSfPOE2AJb+S7OAnxxzRGd9XJp/G0AblSmUyPyv5Qiqauj9QWvH/O80FwqD8tuR2hRNn8AE+SDfdAbtNGu5uJrfqbNOw=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
