apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blocky-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: git@github.com:racela/home-server-argocd.git
    path: setup/config/blocky
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: blocky
  syncPolicy:
    automated:
      prune: true
      selfHeal: true