---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: barman-cloud-credentials
  namespace: cloudnative-pg
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCT80B+G2GrTs5N16dCc5Hc0noQEeZCC/2C65SgMaJ+3p34CpyNUFVo7j8zc3rZWOs/qMa7ra6VDp9l6jIYeGS+PWuBfDrgyyQNqfIAXnF1eyLFtaUtx7K5jaoruxjYPoX7ONaMJrRLFebT7ukMn1Gspgva25BiZmsCWCrs5y/90ze0hFV6oL8ylAd347WoX/wq6hg78JOuvrYvdHXCWdVC8gxysUSYJLwf9dC/AIhGAF7h0bsXhztnMq9IFexNN8PbVEVUviEqd8b6ggMBvKYbAX9sXGTPEwxqqw5EG1MVx/g+yJjoq+60lL/lu1N4+fNHal7v8/W+7tYe4f+i19x31ynOHSzgSVdMUYpSZqnbZUgUX5YI7N+C2iXrkNnEX13D+7UBOkH3+NN/7XN6anS3wtccPHzTQZAdqw/nfsABueJ3jRMFq3RUphuf7KZUTu+rzHqzgyQyIbzMKTpJixkKhSqwIrRoNfgtWDIIa1RGUoZkKiTVVcEIOjSQE/RaGQvRan6VUyy7BsuCL7DZWowWvLxbVGte8++eGXsW80my1baR8+qxzbm/jw2a2ftZnemOwUriuTpwVnhSXs83cswX0Gt/AJs58iIruf5Ocgg31DjysM2SUpb2g7QnWRDXVfhzDNr8siA7Ck+VPWDk18PTakg7+7KlUEps//2d+S45iAsz7tqg/DXipxPPOL8XSyjK3D+p8zKqNboVoQnDIF4WKtG+gO8IYJsi
    ACCESS_SECRET_KEY: AgAxSJObGVik65HKim6hJJIEPY3K5c9SXw4jO8jSnsjLxi7xoyiR1/U4J2F2hjFlFYy/UV37UhtLgrNKEbbcUluLGAfBTapnQY/w2iao/akHz3qsgrG1ndVbTkK5BVbGwU6E03pWpvghK6/UQsDBNikTq26/0rYTMvjCyq6FVMI6iGfLCMgsfkNQCS8vsRBg4wAaWUjdegXclSud5rVYDk1iIYa41Otuh5Rb2dtmcrWrTdoBSaVdn4lyEDaEJyDYEyVUUWaqZvXYvSo0TXEKY987Hni1Or2tXeDSMAspIu1klooLQIyEGSjKIc9exQMwpOjY+AfLRd8CtULocerU+l82R4zlojGYBLV/OdUsYiYn6EfPCtFKU1dj9FANeRphImsDF1V05UNAXg9CTUK6rZktduWN1r5z6U7widlP52xG2MzNIYaXUzTMB84OeE/2UhLQgL2S380Pl/rPm36wzSNmTWGRt6xi/b0GHsHZhbBSTyXHphC2ERl8KqNTLbXyqHahaswl95vOIcyM4ypyHA+hW4/UQGg0cvmv4gdfuraMdf8F6DOV0Y0uTzI+tvtOmlKW9e/V1H+HFAldR0FBmc0YfxKLPxrk/Qm7NBOQbCAu09AkDHfkcoM8T74t5Qc1sdFlGRfLJcpQZW+4nY5hFLfwG5HtUePoEVruMVx3JAMQop2bpfxen6SdO+7qVZdrKL1fp3sHUnQtwUYohC77XYju3ldlk3qryUJ1hQbcsBYf
  template:
    metadata:
      name: barman-cloud-credentials
      namespace: cloudnative-pg
    type: Opaque
