---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cluster-superuser-secret
  namespace: cloudnative-pg
spec:
  encryptedData:
    password: AgDGitOy8sLGngbiF9dUZmajOxEusz1+12t6kiEmkSBDiK/M8PR6CkaCkIE5KOwzdsX8Xi5dD9IQc/ZAN5Z29uZOtxtHkjwbRDEj9kLYZ4guSqWBRwh3tC+90TALVaTHcF4tb6ytV0ckRSIEa8PnvXKIxvXVeb88Nug6rXMy0uhFckgrHf6BCMOR33LahpRydJ9qiBNkRHy+7keH1wD9rMYdoZ83X/g7tTMayKNAi85EQNWBMoWWn8sOA0Wc+3MN4AwSTBCOZ5mo/LYQSPBrhwDq2Lv2jT7PI9XINhH50KQ52GPMsCzfhYp0mZlHkbLwyQBhHjTV8I7lMc3AtskNQU0jweWZ0rTgW40rxBYLPRxSRzfryh7AiypRUbhFJgKqLoi4SUddCzOw3WSmSTse71nRoLNLCCvdUmXD8TskLqoWh4I4KsBPlcDxvurDiPJOsaf+JRjwWYLeF6BhjCY1R6h2Xkh+AW6zVX1z1eZyYAPNdgInWfDchOLcIuOxYU6ev5AzOOgEPl9RUauGzL/HPKFM8taTTWYNjNdfrWDCIoA2XmuaOlSMJJr188U5TwPAMVQGTMcmQt38z5Fah2DQvniJdqeizA6Nh5ty2b3roplBQhL5+oEs4rL7DWashfR7vAFoJDj9AfKCkLoz+SWw2iElCTv7vPDqjVkyhWOT9zpYCMITEZYXxdgpidrE7PZujQdKCU03GiQlbHYLSRPwrMvir/pkHA==
    username: AgB1m4bQktPo1ahQMX+I03W2KtIy6GJlwTkCIhn7r0PK2P4c6JJC2fRDKZbwdnKHMFUIQNXj/spNDjTvCvjKUEWaOOBoc0cz5jFw4ln5tAj89aR5K5LF+MO2WHpKM1WCNvJiM3u3J96D4JRnpfiB67PQdyWAAT1WokDmjfhetjCJyG+7VGTbd14scqHib0wfDbrEzt2KnMq+i5arWxoO0krgyIYIX7UpH/Ud6iCwum8BmWKDdgN0PkA3LK0kMrqhGE7hX26xIT34e06iAG7oraRPWGR871I8Q3fsUNBBogAyB4QTtu5FkAKng7adytjrUaSp5Kh7xL/rn42lFPqk3/bc5p1XgCUpPTRIqNmdm7QrZPU1i/4D5QhSmgV8VglhKuGZPF7qHy6PyUNe7m/H7E+PDpCa5rX9HHPGaW7dXg36y6Z9Q64BglsF9wuJFz48fgPqFlJkbgnsINEy4u7fQ7I4C1BN2rJWAv30Tkd0ujj0ObWh/5GwxD+XIUGk5uWZ/AN02Ot6fTrCSKLVUNYvsP5XFiYYaeVDHrbsoI+qTWzMJdKa7MUiTaTXVJ4BsIjeIAJ9NKszabd+gu60SIxGSkRsN0bMS5EfRapoASHfYkXoljAyhXj97ntPUDvCVavoE2yr9qTD7ktlOBr06sf6r97ZEaP3kC/yIkWsEk/vRIa1Mjc2zvtHthbr/XO96apiy4G+BVC+OYEcCg==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: cluster-superuser-secret
      namespace: cloudnative-pg
    type: kubernetes.io/basic-auth
