---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-db-user-secret
  namespace: cloudnative-pg
spec:
  encryptedData:
    password: AgC+hz2jnYVaHZoqWyGB2G6g5ytqgg/c1RjTUwDVyUhOM7f3WAMAbMBNm2VZExZVOTmhL60+3sEue0nwUQKPA+Be7gN8ElI+zRXq9Of+lbFLaJ1KTTTrXstA7ZSS7L/UEYEA/ZQpmgwAe/5Iyn1sxmuATE3CBgTqE7vcJJNCH1CHanpQsTBtXWOGfsOkvfQHWgDLun4HX1k/L/UF6DpXEhJR7JNQpGJ/ysp06hqlihfKDknaHNcsfQMG2GSuHeQgBZUsCYYb3UL2la07GZfom6T5Qdib5U0KQQs5yUjDHU9eFka+ojebNQihp9naYAFi7A0hokmnADopY72qRfJaEHrkL/vUCnF9butEhNoA9iVqA5YwAXzddO6wf40Eo/viIvpiBa3XH837vTv0zQzVUvJclwdN9Whp1AwQkKss1ctIw04LCY/w1Qp5K3sDeuK4pKD95odVLTy1XJzDwkgzGxeUR7FMzdc7Na5O46ZiXQNUlSi5bkqHQ9l27ol4d6blnvLWfGNmKjhNTC4es0889rKMLXBtnPVSbUjGQQPTelxBn/Lz3mGb3IPnhzNjidFlempB75m+wGhw5WxPBmi1m4P2HO22KMltWuogsdFB3ZkZXYNnUVt8LzgBGJljpJaEr0n2Ax2qh5VX9Io6Kq3U6YuTb3M1cNayEeY/EQ1XrOT2q2+d8jvKIUhCRxyXcTLl99lJHZxBvOz1aWFA2sjMOvrHaHP7dQ==
    username: AgCR70rwcznAQy/xuKVfa2p93HXQ5DoOabUMuUdTiHRFX0CBkM1sBEG6o7C4S24r9LrpDbx+gWp0eo71C7i2bmNsk6FhIy65DYAS0QnRtClL3W+VHdLHKWqqtxYIb2b1zTJeh8queh35+N6L9VM+kPzSqJG0/dAOR7wIcSkGgL1zBVkIjUqbdj4mhQL1idRSvStgttcAw4XUDkfgWsHk0IMsSCVYE0mKK4muSgbhBOXduK06l8086cu9r+JhYjK+QmxzxSs053uN9q9L7sRexVaD4f/RmSNGdfnxEyZVU2fOg2P9tCj7fcDbCS7Xy+nvbox/SKEttPVUUf1X0d305a8QEN30561uLiQfJtEgMokBu/05JTEGoyxv2EWqANrJP4ba7dA9QeK5iDlA1lWOK+YOeDAlZ2K6aPLFVFlITbWixdgvoUf5QSORREl6SeNzL8lQ4Fq2VQpumkPm69NbSpCUmfG6eJsszxW2aC+Rj4K4lZl09Se+NXvh6LR0Vl7MnZPIY1d5q7zWWESAO14uQGA4AwK9f736es6b696EtXYkDhvUmbaipQAFr8DkWLbeOoc7DUiDGu2+T17i/oToU4CvItvPrGRIXbi6+O1CtRbtWkPks+DDpSDhlK0yEOITZ/o7Sj3QNv39WQ/V53yBfdgOOvC38iorU7xouDrb/9i/MkokJkmPN1Y3gTvNvlvondv/3jfeU0o=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: immich-db-user-secret
      namespace: cloudnative-pg
    type: kubernetes.io/basic-auth
