# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: nintendo-museum-alerts-config
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "4"
# spec:
#   project: default
#   source:
#     repoURL: git@github.com:racela/home-server-argocd.git
#     path: apps/config/nintendo-museum-alerts
#     targetRevision: HEAD
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: alerts
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true