apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    chart: gatus
    repoURL: https://twin.github.io/helm-charts
    targetRevision: 1.3.0
    helm:
      releaseName: gatus
      values: |
        env:
          DISCORD_WEBHOOK_URL:
            valueFrom:
              secretKeyRef:
                name: discord-webhook
                key: DISCORD_WEBHOOK_URL
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            cert-manager.io/cluster-issuer: "home-issuer"  
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          tls:
            - hosts:
                - gatus.rafa.local
              secretName: gatus-tls   
          hosts:
            - gatus.rafa.local
          path: /
          pathType: Prefix
        config:
          metrics: true
          alerting:
            discord:
              webhook-url: "${DISCORD_WEBHOOK_URL}"
          endpoints:
            - name: Plex
              group: media
              url: http://plex-plex-media-server.plex.svc.cluster.local:32400/identity
              interval: 1m
              conditions:
                - "[STATUS] == 200"
              alerts:
              - type: discord
                description: "healthcheck failed"
                send-on-resolved: true

            - name: Home Assistant
              group: automation
              url: http://home-assistant.home-assistant.svc.cluster.local:8080/manifest.json
              interval: 1m
              conditions:
                - "[STATUS] == 200"
              alerts:
              - type: discord
                description: "healthcheck failed"
                send-on-resolved: true

            - name: Longhorn UI
              group: storage
              url: http://longhorn-frontend.longhorn-system.svc.cluster.local
              interval: 1m
              conditions:
                - "[STATUS] == 200"
              alerts:
              - type: discord
                description: "healthcheck failed"
                send-on-resolved: true

            - name: Deluge Web UI
              group: media
              url: http://deluge.plex.svc.cluster.local:8112
              interval: 1m
              conditions:
                - "[STATUS] == 200"
              alerts:
              - type: discord
                description: "healthcheck failed"
                send-on-resolved: true

            - name: Grafana
              group: observability
              url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local/healthz
              interval: 1m
              conditions:
                - "[STATUS] == 200"
              alerts:
              - type: discord
                description: "healthcheck failed"
                send-on-resolved: true

            - name: Prometheus
              group: observability
              url: http://prometheus-operated.monitoring.svc.cluster.local:9090/metrics
              interval: 1m
              conditions:
                - "[STATUS] == 200"
              alerts:
              - type: discord
                description: "healthcheck failed"
                send-on-resolved: true

            - name: ArgoCD
              group: gitops
              url: http://argocd-server.argocd.svc.cluster.local/healthz
              interval: 1m
              client:
                insecure: true
              conditions:
                - "[STATUS] == 200"
              alerts:
              - type: discord
                description: "healthcheck failed"
                send-on-resolved: true

            - name: Blocky
              group: dns
              url: http://blocky-http.blocky.svc.cluster.local:4000/metrics
              interval: 1m
              conditions:
                - "[STATUS] == 200"
              alerts:
              - type: discord
                description: "healthcheck failed"
                send-on-resolved: true

            - name: Otterwiki
              group: wiki
              url: http://otterwiki.otterwiki.svc.cluster.local/-/healthz
              interval: 1m
              conditions:
                - "[STATUS] == 200"
              alerts:
              - type: discord
                description: "healthcheck failed"
                send-on-resolved: true

            - name: Immich
              group: media
              url: http://immich-server.immich.svc.cluster.local:2283/api/server/ping
              interval: 1m
              conditions:
                - "[STATUS] == 200"
              alerts:
              - type: discord
                description: "healthcheck failed"
                send-on-resolved: true

          resources:
           limits:
             memory: 256Mi
           requests:
             cpu: 50m
             memory: 128Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: gatus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true