---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-actual-credentials
  namespace: homepage
spec:
  encryptedData:
    ACTUAL_SERVER_PASSWORD: AgBT4CUMxyZFOruX4poK6EwUw8iTY4ybWDpFi6LzLHHAVB4EaiTHan0NKy6fXN50uX1AFw6xqCqICrACFeF7cBVgiGzCMD8rGl8gUTBfEj9OrctiBGT2O/QJI0fGwKMiUe6iolTjdzrQEJGIVnQgz8NdiDnjk6JUptDYoKOzl8WrAivZKjaULtHYahICz2x3QyJzX2K86fjq76/g9WhnrRoq9jkSNZUCUaWtWJnE+eNU5clcopiX/dOknHCxd1C7yb0QohqZsrkFZPNfC4zm8CIUqIK5S4m4Jbxu4Cssg80X+Lfr9j9qZ03qeAq8lGCfRD508Wvedyg6tB28Tz7IodRJDRspDp0ZrA3K0Z2LotXTzeV1A9fZg5j2lGYswq4Syy9AIeHngNuu8ADdGU7mp+aC17wKNXfFR1uXQrXWMmccE62Ou4ymFbOfM8hZbTjB/BiVQ6UnWgf7HfZ7Ye3mK2oF097eCfogJNMb2zg6LxOywWRrLGOcZd/wbozd/5iD18MZBBwHZEUd1EQxPLN1outQhIeeILu/UaspQ8rYkPhluceUgrNYRMFl4t7FD4vA4Nch+GklLfDPrwRzGKLMzPgPlUsLWmdfb8uyCcNQaAtWI5foip4oX6kLV/DoTAHFfHSjLMfR9egXtY5Z7IbkjVUZswNAsszRNWlyQdW1pixlQvU0oUqUmoqhlbYMLd8SBUsN2o8IL8Fr6+V4r1pVZvA=
    ACTUAL_SYNC_ID: AgCPwVcR/uV4ihKAv6cysyAE3TmGWPiRqfwjgdsxaSiEuZeN39nBaZ2Iqpgna33irC8aqsVloAnVUbYZyXzMkPRQLt4XxVlO3DWcgMfbHw/X50B4zobRdfKf4y281+crzT4RvlaONDJOg3SVxE6bqUl6DK7X1nMAT8p/Rd3+pSJuO/B5OqrsobAlrhxjZuyPd2tU2YgxGc54Y/5gY83IXB9nkoLfnWgmr8/7tBTTsG5xsIt+QwWhfLKbqHWGgVSNcIT5xq1tVd9U0Gr4DD9n/EwPw8Qzfu75YeNw315NEleV2XRQT9z7wRiLpSz9dcRTRxPH+K2FNgYhkdryQgGNh0OBEnwabD3YV2VZ4sr17Hr9gH48lokYN62ZAavKGvamKNJEkp8kwpxlb9w2ULuEI7xpJVNdNu4HmbPLS61kkAnZOf3bYIj7yizOjVuGxugyQN4imunE7Hr9qUr4LW+rhYl9HeKIgJhA+LWYtx1HpAEdZKlTSwolQKHF8huUm67b8sB91l8OnzEffQ2d63zsk08oVlecFLJm3U3sjHdl7p2ISWRJ+0gdI2ARqe7vcpGXZlFDHIRgywzie7+no95AD9peuIN/Gk1+0ir5l2oDwD6/GykfeY3XtR8K6wwu92fz9ZXuAWUDv+9xpNk+Ww8PfcZb09/iKm3EvchGQYWFy89hv2iNig+wklYtdrQtpPjNx/O0PvuHC3b/hfSDXDf5SSz3yzQh2hWcC5P3/gBM3QTrk9lsXDI=
  template:
    metadata:
      name: homepage-actual-credentials
      namespace: homepage
    type: Opaque
