apiVersion: v1
kind: Service
metadata:
  name: deluge
  namespace: plex
spec:
  selector:
    app: deluge
  ports:
    - name: web
      port: 8112
      targetPort: 8112
    - name: daemon
      port: 58846
      targetPort: 58846
    - name: inbound
      port: 6881
      targetPort: 6881
    - name: inbound-udp
      protocol: UDP
      port: 6881
      targetPort: 6881
  type: ClusterIP