---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plex-claim-secret
  namespace: plex
spec:
  encryptedData:
    plex-claim: AgDFL/Ln5xCjC9LcCX4Q4PojPc+jey8e9Y7P3Ek0Qiz0ekrDTy+erNKre69xoAt9TO8QYv7DIWFrS3CmnoyXpXZeN17OlutbMcFq1b6DlaOQtJd2GMywdAzjBZTdMJJxHPYJWF1j731AZ4nDJGG+DO3kgbQvTgHTOu/MJvm+DN7B/z8R0mYaTZeLkODcFej4BR3ccG/igTXkPHGD+J2vRaXOC/RpkeJ+v2jk6vKKvGa7ux9ZeHuWUr7lpbQwsbOz/mlgfUfV1ZGgwL2hkb1mC+mjY8G8sZORlVy12j8I0X7ju08T8Pb9na2aVh/Fe9MSzejwaQ3vF2wSMKKLuSOjbV8OFcfU1XJ/EVCiLdqEw1jbfCzyifNLg9BxmvqEOIElXJihKFcQ5UwZnClJqhCQxbYqpuXH6tYVsUHKe3d2ckCgR/ylBNk/g4eExrQZaaqu20lxL03sX/9N1/V8cV5gxVldG1RqDLsuZfuFjUAAcnkqd82MYbr1Qb88Cju7Kmk0G9E/o8k5HKIHzRMGbFBuU8P4nKel0b0Fzc+V7YFHO0D82/3GRSBCHqOWYeIp6CXGiUKSA3FWpz4UFXhcm/7ZUORLMpeeWTm5ErAfbQEYDYT5ghm0BcjDPFRZCEeJrScd89VBiHkwJyxLQVRpmnUpYfh3bL2xNOL8vn5Oj/vZrxuHfbqwzqJqdQmhdfeytG+vlGmZaZ91KWN1kwmGQsLxmBgbceL9hhkv8vn+SVE=
  template:
    metadata:
      name: plex-claim-secret
      namespace: plex
    type: Opaque
