apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: plex
  annotations:
    # Use the nginx ingress controller
    kubernetes.io/ingress.class: "nginx"
    # Redirect HTTP → HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # cert-manager will use this ClusterIssuer to issue certificates
    cert-manager.io/cluster-issuer: "home-issuer"  
    # Tell nginx to speak HTTPS to the service
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # Show real IP
    nginx.ingress.kubernetes.io/proxy-real-ip-cidr: 0.0.0.0/0
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  tls:
    - hosts:
        - plex.rafa.local
      secretName: plex-tls            # cert-manager will create this Secret
  rules:
    - host: plex.rafa.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex-plex-media-server       
                port:
                  number: 32400