apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-movies-pvc 
  namespace: plex              
spec:
  storageClassName: "nfs-csi"
  accessModes:
    - ReadWriteMany         
  resources:
    requests:
      storage: 1Ti           