apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-movies-pvc 
  namespace: plex              
spec:
  volumeName: plex-movies-pv
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany         
  resources:
    requests:
      storage: 500Gi       