apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc 
  namespace: plex              
spec:
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteOnce            
  resources:
    requests:
      storage: 2Gi           