apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-series-pvc 
  namespace: plex              
spec:
  volumeName: plex-series-pv
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany         
  resources:
    requests:
      storage: 1Ti           