---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backup-telegram
  namespace: immich
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgBSZcrJa8NNi51iZbXdnWZmYrSkS4TUo1+nRlOdJEu3P64fRLDoY+BvJdfI3JM/NHG38MA3ZqDtOcIwl6JVvkCNeP0ay51l5b2Hx+51WeSedfijWfnWh6JWnAJIUlrI3ip28rjly2PLicHbh+mB/8HrLJCB+S9CwrfMV7ARrutdA7JdEaGKLykKR+xb/BTny/1wYxzKuk8CbMlo7uZDIbmE4Cg7IW0d+5q/HJsaelseSzkj7ygfdzgy2Ivy6olFAsqq1vMHl0dPC3SLAkjwLWTg4ys0M4BWRMR/R4t80jOxs4eZ6tKAeTSgtOdnly821zuW7Lu0YCE8WOYPHSSZK+qlwpOTFboi3w9k5cskpbmMeub07ZitjXA7VKqZTEyJ/31cZ9UNTGRyzL25vpykFOqdMhl8QxPQ5jbEAPiVSo+pSVGsp4fJk4dUkNDvQ39PasHZh0OUQgRdXrBLumKaVfZLdm46WU5Upka4ZdqN42VwbEMPKQSpzsirsFyWEmGlXoRkxNbD8LzVFrZMRwc6UAa2n077+kZcVPVU4KOYWFek1tILofac8LJAQiGsBjZ0gQLtGlnSs5HpgO3xkNkDIZBBB059SfqK5r58umUFRI4kVh7R/mNJoe9xJzU4c7wdBq9X67X1j0I2YkHRkLDJG3zwZiYuipWR55cfkuh3BZS57N5/lH1OVQRnZKBIFlp0pooYMMQG0VJWLNJBxjKy4bkI1i492lAjIxVeZj5mDndq2K9qrki9Plauc34A+0f7
    TELEGRAM_CHAT_ID: AgCUMOxxIw7Wq4eKiFK5JpDVYejSo90HBRn/fAzK+ts5exbOQBy3jD9fsJBCDGy/SmwvTBF38bTzBFyHU5Xutc3pUayYCrbZdP0kKLdtK+ONPXFhV1s73KTBw8X2zZQ+2+MoAXrBd9p/x+P4xyer2+g8sItGyUD43YaFvmw8NWgJxfgcT+fRgGNTWG+LKTfh+bSuUTAsGZ/XO8qGyJe4OfY+wCL4w5dGSHSTO6txIBa/nm3bMapR7lBPdlEzlguwMvdMpZiG0F5gS0aCByg4B6/cvJnnEUCSAp+OmXrbx5AptL1v/hCqKi2EcgrIBMnMh87wGixM7CdL5LW9HVPaMpuLRvucq6EsUzOja2rMGkamnobxHZTprMe8rTbA0GHH1QnQWTQtx1v0cSjBXJIw4lGclo+YZkZLfG+csr8LZuu3usad8pz6exw/JUdK125tKRvCAEMg3e6Sk9dTQ2FI0jwe0RxX14vnhhip+oflc67MhgWB7tMSnnMvHY5bQBFsyksRz/QnXdk/MDFyPHbbKlWd84vgIjnWn6qi+I1PFQLjtNTWWkGWFVHcAIDNT4TnR4CyfRYTB6ycQhnX3SP44p608L7OKU0Zu/H3ymJWHpF5rkCVxOjd6CR9lwarSV0FNmEmB+Zu+7R78UONBpT5BWEqvHG0DHUxUBHAcT6vv/yqGO8sGXc51IIbAbxaZMx3UCCc9o4q96I+8qdb
  template:
    metadata:
      name: backup-telegram
      namespace: immich
    type: Opaque
