---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gatus-backup-reporting
  namespace: immich
spec:
  encryptedData:
    token: AgBam0sM3fuDO9+yDjoTmwhW+4E/KJac7/MXDwrhnT3iQbRlUiO+NSfcgNz825WRpECkbUnTzI8l5Hv4lvIPMsqRYSvz8rffey8YF+iFhdSdvb8BZgGBwGyU93z/zK6PC5nZJ0ohXEFYvfTKg2DbBUuCClIdLmuwbhw84tltzZxSdsdaGMlXu3uvXye91s1hO57iJ3ESwlQAWAP5OtqLy3JkOorsfiCfvSKVMYhobotxhJBVdTAMaJAcWP8RxHAcWFKiEg5bL3XEdqlJSYTdE20BTXz5RUfPVAu2AcVw/AtfF5mpnCi275w2RAFEcD1w6fs/NKbV6+LjL3MN/5iRaPH9Qz84qwAdWj1fhkOwh+ilIhm/HJBJqpJtEuxxNuy8RggIfrg1nfzH6Xf0UN4ws+ZaEv5W3fXZbcLJbO1vgI2Vi5HBm+95nc5IF2eRUMee+qbdqBFJJc7cfCx6IuScutU/ACqV9SJn9LOUujJyKUEOR54zqsa5EpMcAgQFGOjLBOzhXoux/afdtmpW+z16aZJrC+hAqEukbWqusEriE1FKSOJULNVu7/q+9xvqwaPr4Zz+vLOXK4REqMxR0rduWBT5td/mz+RTMbA5odFEjltTqxTPELMbDdU1ewlhGBGIBreGKE9aeaqlSVivrWou0dHdUqB/ISBwCDr9lfhVbi4W8abgoE9NCssu/pLfuLLMzpdKritu/5fd1rjnuaihGxkqD6+9nl7czK9ImtVPpudNrnnhRyLNZIlJAFqw
  template:
    metadata:
      name: gatus-backup-reporting
      namespace: immich
    type: Opaque
