---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-db-secret
  namespace: immich
spec:
  encryptedData:
    password: AgC7oypJ65Q+2ob+NW23A+DyQcBshzweT1ZOJpN+TQ3FJ9ZGrOSfDUmsCPj2EO4e8F6W+E7lA1yQwA+9djLT3eXCcOentpVL68gqYhyOILRtM/igXkdFZ0MYlT90aKkGygy+W4Pctl5jeJhr8XfZqocFkeezaSDTcV7vukIbzUGqnTFwuA8FGrrVRzKvi4K0bq8AKbu7v4MIgje2MNecj7XLqFy3QxhrxYUGl+FZplAFKRGnbuOjG5O5RglZdBD79iEYuWrl+RJV/fwyL9MYdX/zeIXXtmb+rVi76G08YjEDGA/Qgg5o38ToyGYS4vPYHLSQPg9DS/dd+oB7OhEk000x6T4Sj5XtbUsWCSCkrUghqIxytk+pVEfjA1kWwRMOpyTLwyqGGwPRxMWc8TNNgcv1YEd0mL4Mf5D3IyJVsBx1LhbzEbx4QX1Ac5QIyRVVeTs13uJrx5PUty1gJnVCk2zbkasgmMqATr+bCXjut9UrkJrw86R+R//BZtimFg1BsP3DUcPtnaszg2L/8a0ZQ+GtbsbRhH2+BKfjRqN1zaeVwtAUnYcIXOWyiZv82uWIwiE8YHjL/+XSnx45+g1XxmijlSxbsks3tmN0V5hw9OQpuaUOe/prDP3GyBJTTWyIqQVXWzUnopddvcQ34nIinxB/ZpE5fz5v/Nou6kfjDIU9qk2zpk1V5dsVuiwmt2mOgZ9NEiAtYDtXEzClhgrm1OrtjM3/Jg==
  template:
    metadata:
      name: immich-db-secret
      namespace: immich
    type: Opaque
