apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc 
  namespace: immich              
spec:
  volumeName: immich-library-pv
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany         
  resources:
    requests:
      storage: 100Gi       